# Adopted from https://github.com/rsp/travis-hello-modern-cpp/blob/master/.travis.yml

sudo: false
language: cpp
compiler:
  - gcc
  - clang
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-xenial-8
    packages:
    - g++-8
    - clang-8
install:
- "[ $CXX = g++ ] && export CXX=g++-8 || true"
- "[ $CXX = clang++ ] && export CXX=clang++-8 || true"
script:
  - cd WithDependencyInjection && make -j8 && ./runTests