# Adopted from https://github.com/rsp/travis-hello-modern-cpp/blob/master/.travis.yml
sudo: false
language: cpp
compiler:
  - gcc
  - clang
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-xenial-8
    packages:
    - g++-7
    - clang-7
install:
- make get-deps
- "[ $CXX = g++ ] && export CXX=g++-7 || true"
- "[ $CXX = clang++ ] && export CXX=clang++-7|| true"
script:
  - cd WithDependencyInjection && make -j8 && ./runTests